name = "job-scraper-worker"
main = "src/worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"

[[d1_databases]]
binding = "DB"
database_name = "job_scraper_db"
database_id = "9a9ddf04-76e3-46a3-ae67-a0d1545c3d2e"

# R2 bucket for data exports
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "job-data-bucket"

[triggers]
crons = ["0 6 * * *"]  # Run daily at 6 AM UTC