name: Weekly YC Job Analytics

on:
  schedule:
    # Run every Sunday at 8:00 AM UTC (3:00 AM EST)
    - cron: '0 8 * * 0'
  workflow_dispatch:
    inputs:
      days_back:
        description: 'Number of days to analyze'
        required: false
        default: '7'

jobs:
  analytics:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Create output directories
      run: |
        mkdir -p analytics_output
        mkdir -p reports
    
    - name: Test environment
      run: |
        echo "=== Environment Test ==="
        python --version
        echo "Working directory: $(pwd)"
        echo "Available space: $(df -h .)"
        echo "Python packages: $(pip list | grep requests)"
        echo "========================"
    
    - name: Run Simple YC Job Analytics
      env:
        WORKER_ENDPOINT: ${{ secrets.WORKER_ENDPOINT }}
      run: |
        cd spark-analytics
        python simple_analytics.py --days-back ${{ github.event.inputs.days_back || '7' }}
      continue-on-error: true
    
    - name: Check outputs (always run)
      if: always()
      run: |
        echo "=== Output Check ==="
        ls -la analytics_output/ || echo "No analytics_output directory"
        ls -la reports/ || echo "No reports directory"
        find . -name "*.json" -o -name "*.md" -o -name "*.txt" | head -10 || echo "No result files found"
        echo "===================="
    
    - name: Upload analytics results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: yc-job-analytics-${{ github.run_number }}
        path: |
          analytics_output/
          reports/
        retention-days: 30
    
    - name: Display summary (always run)
      if: always()
      run: |
        if [ -f analytics_output/latest_summary.txt ]; then
          echo "=== Analytics Summary ==="
          cat analytics_output/latest_summary.txt
          echo "========================="
        else
          echo "❌ No summary file found - checking for any output files"
          find . -name "*summary*" -o -name "*report*" -o -name "*analysis*" | head -5
        fi